import { useData } from '../context/DataContext';

export function usePlayers() {
    const {
        players,
        addPlayer,
        updatePlayer,
        deletePlayer,
        updatePlayerFriends,
        removePlayerFriend,
        sendFriendRequest,
        acceptFriendRequest,
        declineFriendRequest,
        getPlayer,
        addMatch
    } = useData();

    const createPlayer = async (name: string, avatar: string, pin?: string) => {
        return addPlayer(name, avatar, pin);
    };

    const autoFriendship = async (participantIds: string[]) => {
        try {
            // Pairwise friendship for all participants
            for (let i = 0; i < participantIds.length; i++) {
                for (let j = i + 1; j < participantIds.length; j++) {
                    const p1 = participantIds[i];
                    const p2 = participantIds[j];
                    if (p1 && p2 && p1 !== p2) {
                        await updatePlayerFriends(p1, p2);
                    }
                }
            }
        } catch (error) {
            console.error('❌ Error in autoFriendship:', error);
        }
    };

    const saveMatch = async (
        gameType: any,
        team1: string[],
        team2: string[],
        score1: number,
        score2: number,
        endedBy: any,
        penaltyWinner?: 1 | 2,
        forfeitLoser?: 1 | 2,
        dateParam?: number,
        tournamentId?: string,
        tournamentFixtureSlot?: number
    ) => {
        const allParticipants = [...team1, ...team2];

        // Construct Match Object
        await addMatch({
            id: '', // Will be generated by Firestore
            date: dateParam || Date.now(),
            type: gameType,
            players: { team1, team2 },
            score: { team1: score1, team2: score2 },
            endedBy,
            penaltyWinner,
            forfeitLoser,
            tournamentId,
            tournamentFixtureSlot
        });

        // Auto-friendship
        await autoFriendship(allParticipants);

        return true;
    };

    const addFriend = async (hostId: string, friendId: string) => {
        await updatePlayerFriends(hostId, friendId);
    };

    const removeFriend = async (hostId: string, friendId: string) => {
        await removePlayerFriend(hostId, friendId);
    };

    const getFriendsOf = (playerId: string) => {
        const host = getPlayer(playerId);
        if (!host) return [];
        return players.filter(p => host.friends.includes(p.id));
    };

    const loading = false; // Placeholder

    return {
        players,
        loading,
        createPlayer,
        updatePlayer,
        deletePlayer,
        saveMatch,
        addFriend,
        removeFriend,
        sendFriendRequest,
        acceptFriendRequest,
        declineFriendRequest,
        getFriendsOf,
        autoFriendship
    };
}
