import { useData } from '../context/DataContext';

export function usePlayers() {
    const { players, addPlayer, deletePlayer, updatePlayerFriends, getPlayer, addMatch } = useData();

    const createPlayer = async (name: string, avatar: string, photoURL?: string) => {
        // Wrapper to match previous signature if needed, or update consumers
        return addPlayer(name, avatar, photoURL);
    };

    const saveMatch = async (
        gameType: any,
        team1: string[],
        team2: string[],
        score1: number,
        score2: number,
        endedBy: any,
        penaltyWinner?: 1 | 2,
        forfeitLoser?: 1 | 2,
        dateParam?: number
    ) => {
        // Construct Match Object
        await addMatch({
            id: '', // Will be generated by Firestore
            date: dateParam || Date.now(),
            type: gameType,
            players: { team1, team2 },
            score: { team1: score1, team2: score2 },
            endedBy,
            penaltyWinner,
            forfeitLoser
        });
        return true;
    };

    const addFriend = (hostId: string, friendId: string) => {
        updatePlayerFriends(hostId, friendId);
    };

    const getFriendsOf = (playerId: string) => {
        const host = getPlayer(playerId);
        if (!host) return [];
        return players.filter(p => host.friends.includes(p.id));
    };

    const loading = false; // Placeholder

    return { players, loading, createPlayer, deletePlayer, saveMatch, addFriend, getFriendsOf };
}
